---
name: Hello World Workflow

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        required: false

jobs:
  say:
    name: "Say Hello [name: ${{ github.event.inputs.name || 'World' }}]"
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, ${{ github.event.inputs.name }}!
      - run: sleep 30

  finish:
    name: "Wait for say ${{ github.event.inputs.name }} to finish"
    needs: say
    runs-on: ubuntu-latest
    steps:
      - run: echo Done!
