---
name: Hello World Workflow

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  build:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - run: echo Hello, ${{ github.event.inputs.name }}!
