---
name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        required: false
  workflow_call:
    inputs:
      name:
        type: string
        description: 'Who to greet'
        required: false

jobs:
  say:
    name: Say Hello ${{ github.event.inputs.name || 'World' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, ${{ github.event.inputs.name || 'World' }}!
      - run: sleep 10

  finish:
    name: Wait for say ${{ github.event.inputs.name || 'World' }} to finish
    if: ${{ github.event.inputs.name != 'none' }}
    needs: say
    runs-on: ubuntu-latest
    steps:
      - run: echo Done!
