---
name: Use custom action

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        required: false
        default: 'World'
      skip:
        type: boolean
        description: Skip action?
        default: false
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz

jobs:
  say:
    name: Say Hello ${{ github.event.inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event.inputs.skip != true }}

      - uses: ./.github/actions/say-hello
        if: ${{ github.event.inputs.skip != true }}
        with:
          who-to-greet: ${{ github.event.inputs.name }}

      - name: inputs
        run: |
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }} / ${{ inputs.boolean }}"
          echo "choice is ${{ github.event.inputs.choice }} / ${{ inputs.choice }}"
