---
name: Use custom action

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        required: false
        default: 'World'
      skip:
        type: boolean
        description: Skip action?
        default: false

jobs:
  say:
    name: Say Hello ${{ inputs.name }} ${{ inputs.skip == 'true' && '[skipped]' || ''}}
    runs-on: ubuntu-latest
    steps:
      - name: Print options
        run: |
          echo name is ${{ inputs.name }}
          echo skip is ${{ inputs.skip }}

      - uses: actions/checkout@v4
        if: ${{ inputs.skip != 'true' }}

      - uses: ./.github/actions/say-hello
        if: ${{ inputs.skip != 'true' }}
        with:
          who-to-greet: ${{ inputs.name }}
