---
name: Use custom action

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        required: false
        default: 'World'
      skip:
        type: boolean
        description: Skip action?
        default: false
      environment:
        type: environment
        description: Environment to deploy

jobs:
  say:
    name: Say Hello ${{ inputs.name }} ${{ inputs.skip == true && '[skipped]' || ''}}
    runs-on: ubuntu-latest
    steps:
      - name: Print options
        run: |
          echo name is ${{ inputs.name }}
          echo environment is ${{ inputs.environment }}
          echo skip is ${{ inputs.skip }}

      - name: Always skip
        if: false
        run: echo "DON'T print this!"

      - uses: actions/checkout@v4
        if: ${{ inputs.skip != true }}

      - uses: ./.github/actions/say-hello
        if: ${{ inputs.skip != true }}
        with:
          who-to-greet: ${{ inputs.name }}
